platform:
    - x64

cache:
    - C:\Users\appveyor\.esy
    - C:\Users\appveyor\.esytest

environment:
   HOME: C:\Users\appveyor

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g rimraf
    - npm install -g esy-bash@0.1.22
    - npm install -g esy@0.2.9
    - appveyor-retry esy install

build_script:
# Reset %PATH% to avoid cygwin DLL conflicts with cause
# *** fatal error - cygheap base mismatch detected
    - echo $PATH
    - set PATH=C:\Windows\System32;C:\Program Files\Git\cmd;C:\Windows;C:\Program Files (x86)\nodejs;C:\Users\appveyor\AppData\Roaming\npm;C:\projects\esy\node_modules\esy-bash\.cygwin\bin;C:\Program Files\AppVeyor\BuildAgent;C:\Windows\System32\WindowsPowerShell\v1.0;
    - C:\projects\esy\_build\default\esy\bin\esyCommand.exe --help
    - npm run make:bootstrap
    - npm run make:test
    - npm run bootstrap:make-release-package

artifacts:
    - path: _platformrelease/*.tgz
      name: Windows Build
      type: File

deploy:
    - provider: GitHub
      repository: esy/esy
      auth_token:
          secure: J4V6+1KHu8UiApItmxPWArb5oMf1WnQyAc9H4GtBzEo620zFin0oRLYQ0DxCz1VW
      draft: false
      prerelease: false
      force_update: true
      on:
          appveyor_repo_tag: true

test: off
