platform:
    - x64

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g esy@0.2.11
    - appveyor-retry appveyor-retry esy install

build_script:
     - esy build
     - npm run build:copy-frs
     - npm run test:unit
#    - npm run make:test
#    - npm run bootstrap:make-release-package

artifacts:
    - path: _platformrelease/*.tgz
      name: Windows Build
      type: File

deploy:
    - provider: GitHub
      repository: esy/esy
      auth_token:
          secure: J4V6+1KHu8UiApItmxPWArb5oMf1WnQyAc9H4GtBzEo620zFin0oRLYQ0DxCz1VW
      draft: false
      prerelease: false
      force_update: true
      on:
          appveyor_repo_tag: true

test: off
